### ISSUE TITLE
Not possible to remove the last page

### ISSUE THREAD

**Issue by Mattijah** [uias/Pageboy#208]
If there is only 1 page left, calling `deletePage` seems to have no effect at all. The view controller will still stay in, displayed. Is this an expected behaviour or a bug?

On top of that, if I pass `.scrollToUpdate` the `viewController(for pageboyViewController:)` will be called with an index of `-1`. Again, doesn't matter if I return `nil` or a blank VC. Nothing changes. *It should not be called with `-1`.

Calling `reloadData` doesn't help either.

Version: 3.1.0

**Comment by msaps** [comment]
@Mattijah will check it out 👍

**Comment by Coeur** [comment]
@Mattijah, currently on master branch, I don't have your behavior; when I delete the last page, I get a `Fatal error: Index out of range`. And this is fixed on the branch https://github.com/uias/Pageboy/tree/feature/insertion-fix

**Comment by Mattijah** [comment]
@Coeur I use `Pageboy` as a part of [`Tabman`](https://github.com/uias/Tabman). I have just tried to delete the last page again, there is no error and the application is just continues running normally. The page (ViewController) is still displayed and still present in the hierarchy. `pageCount` also returns the same number (1) after `deletePage(at: 0, then: .doNothing)` was executed.

**Comment by Coeur** [comment]
My test was using the example app, which uses `deletePage(at: index)`: https://github.com/uias/Pageboy/blob/master/Example/Pageboy-Example/PageViewController+Bulletins.swift#L59

Well, anyway, crash or not, it's being acknowledged that there is a problem to solve there.

**Comment by msaps** [comment]
@Mattijah @Coeur fixed in [3.2.2](https://github.com/uias/Pageboy/releases/tag/3.2.2) 🍾
